import type { ProjectIcon, CategoryIcon } from "../model/types";
import {
  Server,
  Code,
  Bot,
  FolderOpen,
  FolderKanban,
  Layers,
  Box,
  Container,
  Database,
  Cloud,
  Globe,
  Smartphone,
  Monitor,
  Laptop,
  Cpu,
  CircuitBoard,
  GitBranch,
  GitCommit,
  Github,
  Terminal,
  FileCode,
  Briefcase,
  Building,
  Home,
  Rocket,
  Zap,
  Star,
  Heart,
  Bookmark,
  Flag,
  Target,
  Crosshair,
  Bug,
  Wrench,
  Sparkles,
  CheckCircle,
  AlertCircle,
  AlertTriangle,
  Info,
  FileText,
  FileCheck,
  Clipboard,
  ClipboardList,
  List,
  ListChecks,
  ListTodo,
  Layout,
  LayoutGrid,
  BarChart,
  TrendingUp,
  Activity,
} from "lucide-react";

type IconComponent = React.ComponentType<{ className?: string }>;

export const PROJECT_ICON_MAP: Record<ProjectIcon, IconComponent> = {
  Server,
  Code,
  Bot,
  FolderOpen,
  FolderKanban,
  Layers,
  Box,
  Container,
  Database,
  Cloud,
  Globe,
  Smartphone,
  Monitor,
  Laptop,
  Cpu,
  CircuitBoard,
  GitBranch,
  GitCommit,
  Github,
  Terminal,
  FileCode,
  Briefcase,
  Building,
  Home,
  Rocket,
  Zap,
  Star,
  Heart,
  Bookmark,
  Flag,
  Target,
  Crosshair,
};

export const CATEGORY_ICON_MAP: Record<CategoryIcon, IconComponent> = {
  Bug,
  Wrench,
  Zap,
  Sparkles,
  FolderKanban,
  CheckCircle,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle: AlertCircle,
  FileText,
  FileCheck,
  FilePlus: FileCheck,
  FileMinus: FileText,
  FileX: FileText,
  FileQuestion: FileText,
  Clipboard,
  ClipboardCheck: Clipboard,
  ClipboardList,
  List,
  ListChecks,
  ListTodo,
  Layout,
  LayoutGrid,
  Grid: LayoutGrid,
  Table: LayoutGrid,
  BarChart,
  PieChart: BarChart,
  TrendingUp,
  TrendingDown: TrendingUp,
  Activity,
  Pulse: Activity,
};

const ENTITY_ICON_MAP: Record<string, IconComponent> = {
  ...PROJECT_ICON_MAP,
  ...CATEGORY_ICON_MAP,
};

const DEFAULT_ICON: IconComponent = FolderKanban;

export function getProjectIcon(name: ProjectIcon): IconComponent {
  return PROJECT_ICON_MAP[name] ?? DEFAULT_ICON;
}

export function getCategoryIcon(name: CategoryIcon): IconComponent {
  return CATEGORY_ICON_MAP[name] ?? DEFAULT_ICON;
}

export function getEntityIcon(name: string): IconComponent {
  return ENTITY_ICON_MAP[name] ?? DEFAULT_ICON;
}
