import type { CategoryColor, CategoryIcon } from "@/entities/project";
import {
  Bug,
  Wrench,
  Zap,
  Sparkles,
  FolderKanban,
  CheckCircle,
  AlertCircle,
  AlertTriangle,
  Info,
  FileText,
  FileCheck,
  Clipboard,
  ClipboardList,
  List,
  ListChecks,
  ListTodo,
  Layout,
  LayoutGrid,
  BarChart,
  TrendingUp,
  Activity,
} from "lucide-react";

export const CATEGORY_ICON_MAP: Record<
  CategoryIcon,
  React.ComponentType<{ className?: string }>
> = {
  Bug,
  Wrench,
  Zap,
  Sparkles,
  FolderKanban,
  CheckCircle,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle: AlertCircle,
  FileText,
  FileCheck,
  FilePlus: FileCheck,
  FileMinus: FileText,
  FileX: FileText,
  FileQuestion: FileText,
  Clipboard,
  ClipboardCheck: Clipboard,
  ClipboardList,
  List,
  ListChecks,
  ListTodo,
  Layout,
  LayoutGrid,
  Grid: LayoutGrid,
  Table: LayoutGrid,
  BarChart,
  PieChart: BarChart,
  TrendingUp,
  TrendingDown: TrendingUp,
  Activity,
  Pulse: Activity,
};

export const AVAILABLE_COLORS: CategoryColor[] = [
  "red",
  "orange",
  "amber",
  "yellow",
  "green",
  "teal",
  "cyan",
  "blue",
  "indigo",
  "purple",
  "pink",
  "rose",
  "gray",
];

export const AVAILABLE_ICONS: CategoryIcon[] = [
  "Bug",
  "Wrench",
  "Zap",
  "Sparkles",
  "FolderKanban",
  "CheckCircle",
  "AlertCircle",
  "AlertTriangle",
  "Info",
  "FileText",
  "FileCheck",
  "Clipboard",
  "ClipboardList",
  "List",
  "ListChecks",
  "ListTodo",
  "Layout",
  "LayoutGrid",
  "BarChart",
  "TrendingUp",
  "Activity",
];
