import type { ProjectColor, ProjectIcon, CategoryColor, CategoryIcon } from "./types";

export const AVAILABLE_PROJECT_COLORS: ProjectColor[] = [
  "blue",
  "indigo",
  "purple",
  "green",
  "teal",
  "cyan",
  "pink",
  "rose",
  "orange",
  "amber",
  "yellow",
  "gray",
];

export const AVAILABLE_PROJECT_ICONS: ProjectIcon[] = [
  "Server",
  "Code",
  "Bot",
  "FolderOpen",
  "FolderKanban",
  "Layers",
  "Box",
  "Database",
  "Cloud",
  "Globe",
  "Monitor",
  "Laptop",
  "Cpu",
  "GitBranch",
  "Terminal",
  "Briefcase",
  "Building",
  "Home",
  "Rocket",
  "Zap",
  "Star",
  "Heart",
  "Bookmark",
  "Flag",
  "Target",
];

export const AVAILABLE_CATEGORY_COLORS: CategoryColor[] = [
  "red",
  "orange",
  "amber",
  "yellow",
  "green",
  "teal",
  "cyan",
  "blue",
  "indigo",
  "purple",
  "pink",
  "rose",
  "gray",
];

export const AVAILABLE_CATEGORY_ICONS: CategoryIcon[] = [
  "Bug",
  "Wrench",
  "Zap",
  "Sparkles",
  "FolderKanban",
  "CheckCircle",
  "AlertCircle",
  "AlertTriangle",
  "Info",
  "FileText",
  "FileCheck",
  "Clipboard",
  "ClipboardList",
  "List",
  "ListChecks",
  "ListTodo",
  "Layout",
  "LayoutGrid",
  "BarChart",
  "TrendingUp",
  "Activity",
];
